version: '3.8'
services:
  pgsql:
    image: postgres:15
    container_name: angular_postgres_db
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:--secret}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
